### PR TITLE
Add column for tags

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by laktak** [comment]
Thank you for your first pull request!

The project uses [black](https://github.com/laktak/todd#contributing) with a slightly longer line length but the options were not included in the project. I've fixed that now. Please merge and run black again so that only your changes are in the diff.

I'd also appreciate if you could put this feature behind a `tags-column` option in `.toddrc` so that it's possible to turn it off if you don't use tags.

**Comment by meatballs** [comment]
My editor runs Black automatically on save and I noticed you used it, so I just let it do its thing. I hadn't realised you had a different line length. Sorry, I'll sort that out.

**Comment by meatballs** [comment]
> I'd also appreciate if you could put this feature behind a tags-column option in .toddrc so that it's possible to turn it off if you don't use tags.

OK. Will do

**Comment by meatballs** [comment]
Ah. I also have isort running automatically on save and it's made some changes. Do you want those kept or discarded?

**Comment by laktak** [comment]
hey, if you want to pick this up again please disable the isort.

**Pull request closed without merging**
